### ISSUE TITLE
Ubuntu 24 support

### ISSUE THREAD

**Issue by msteggink** [clustervision/trinityX#408]
The installation of linux-image-generic takes long (or fails) when proc/sys/dev are not mounted.

Also there is some python issue with 3.12 and Ansible (see also: https://github.com/void-linux/void-packages/issues/47483)

A simple fix:
```
# pip3 install ansible-core --upgrade
# ansible --version
ansible [core 2.15.11]
[...]
```

**Comment by aphmschonewille** [comment]
where does this pip upgrade need to run? inside image or on controller?

**Comment by msteggink** [comment]
Controller node requires it.

**Comment by aphmschonewille** [comment]
confirmed. The role only installs slurm from epel if openhpc is disabled:

```
- name: Install slurm packages
  yum:
    name: '{{ **slurm_packages** }}'
    state: present
  tags: install-only
  when: enable_openhpc == false

- name: ensure legacy slurm rpms are not installed before configuring ohpc versions
  yum:
    name: '{{ **slurm_packages** }}'
    state: removed
  tags: install-only
  when: enable_openhpc == true

....

- name: Install ohpc slurm packages
  yum:
    name: '{{ **slurm_packages_ohpc** }}'
    state: present
  tags: install-only
  when: enable_openhpc == true

```

There is no risk installing wrong packages during TrinityX installation.
