### ISSUE TITLE
Network DNS setting

### ISSUE THREAD

**Issue by msteggink** [clustervision/trinityX#409]
a.b.c.d is not overriding 10.141.255.254 (defaults)
```
luna cluster
+---------------------------------------------------------------------------------+
|                               Cluster => mycluster                              |
+---------------------+-----------------------------------------------------------+
| nameserver_ip       | 10.141.255.254                                            |
```

Network:
```
 luna network show cluster
+------------------------------------+
|         Network => cluster         |
+--------------------+---------------+
| name               | cluster       |
| type               | ethernet      |
| zone               | internal      |
|                    |               |
| nameserver_ip      | a.b.c.d   |
```

RHEL9:

```
 cat  /etc/NetworkManager/system-connections/Connection_eth0.nmconnection
[connection]
id=Connection_eth0
type=ethernet
interface-name=eth0
autoconnect=true
zone=trusted

[proxy]



[ipv4]
dns=10.141.255.254
```

Ubu 24:
```
cat 99_config.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
[...]
      nameservers:
        # ns_ipv4_eth0
          search: [cluster,ib,ipmi]
          addresses: [10.141.255.254]
        # ns_ipv6_eth0
```
