### ISSUE TITLE
Missing slurm-munge, slurm-plugins, and slurm-sql on RHEL9

### ISSUE THREAD

**Issue by mulderij** [clustervision/trinityX#418]
Running 'ansible-playbook controller.yml' on RHEL9.4 resulted in the error below:
```
2024-06-05 11:37:46,436 p=55190 u=root n=ansible | TASK [trinity/slurm : Install slurm packages] ****************************************************************************************************************************************************************
2024-06-05 11:37:48,347 p=55190 u=root n=ansible | fatal: [controller1]: FAILED! => {"changed": false, "failures": ["No package slurm-munge available.", "No package slurm-plugins available.", "No package slurm-sql available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```
It is true that I don't have any repo with these packages available, but which repo's would that be?
They only appear to exist for openSUSE: https://pkgs.org/search/?q=slurm-plugins

**Comment by aphmschonewille** [comment]
Hi there.

Reading your problem, make me think whether you have disabled openhpc. In that case the below section is being called.

```
- name: Install slurm packages
  yum:
    name: '{{ slurm_packages }}'  <-- containing slurm-munge
    state: present
  tags: install-only
  when: enable_openhpc == false
```

Since we rely on epel providing these packages, i think there has been a change there.
Could you confirm if this while having enable_openhpc set to false?

-A
