### ISSUE TITLE
Creating new RHEL 8 Image breaks on repo task

### ISSUE THREAD

**Issue by xdkreij** [clustervision/trinityX#431]
**Executed**
LC_ALL=C.UTF-8 ansible-playbook compute-redhat.yml -e "image_name: testimage" -v

**Issue**

![image](https://github.com/user-attachments/assets/eeaed75f-69ae-4f10-a051-2b114f212661)

**Cause**
`roles/trinity/repos/vars/RedHat8.yaml`

```
external_repository_rpms:
  - name: https://www.elrepo.org/elrepo-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.elrepo.noarch.rpm
    file: elrepo-release.rpm
    no_gpgcheck: True
  **- name: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/e/epel-release-8-19.el8.noarch.rpm**
    file: epel-release.rpm
    no_gpgcheck: True
```

epel-release-8-19.el8.noarch.rpm is hardcoded and does not exist anymore

![image](https://github.com/user-attachments/assets/f41c949a-fac2-4fc0-8857-b5ea9d798ced)

**Expected results**
- required rpms to be installed
