### ISSUE TITLE
Rocky-9: PowerTools is now CRB

### ISSUE THREAD

**Issue by mulderij** [clustervision/trinityX#474]
When using the Rocky-9 distribution for image creation (`alternative_distribution: Rocky-9`), the playbook crashes on installing slurm. This is a result of a repo name change within Rocky-9 (PowerTools -> CRB): https://wiki.rockylinux.org/rocky/repo/#notes-on-crb

```
TASK [trinity/slurm : Install slurm packages] ***********************************************************************************************************
fatal: [base-rocky9.osimages.luna]: FAILED! => {"changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - nothing provides perl(Switch) needed by slurm-openlava-22.05.9-1.el9.x86_64 from epel", "rc": 1, "results": []}
```

The role 'slurm' has a fixed action to enable the powertools-repo (https://github.com/clustervision/trinityX/commit/75893f56355bb11baf126923eaf7112983eba809)

```
- name: Install slurm packages
  yum:
    name: '{{ slurm_packages }}'
    state: present
    enablerepo: powertools
  tags: install-only
  when: enable_openhpc == false
  retries: "{{ rpm_retries | default(3) }}"
  delay: "{{ rpm_delay | default(15) }}"
```
